version: '3.8'

services:
  web:
    
    build: .
    
    ports:
      - "8080:80"
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__OracleDbConnection=User Id=RM551353;Password=190204;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=db)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))
    
    depends_on:
      - db

  db:
    
    image: gvenzl/oracle-xe:21-slim
    
    environment:
      ORACLE_PASSWORD: "190204"
      APP_USER: "RM551353"
      APP_USER_PASSWORD: "190204"
    
    ports:
      - "1521:1521"
      - "5500:5500"
    
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:


